fix conftest.py
RedRoverSchool/Saucedemo_05 pull request #12
Opened 2022-11-19 15:24 UTC by rgirl0801

2022-11-19 22:04 UTC, akioikeda commented on tests/test_inventory.py
> +from constants import SOTRING_AZ, SOTRING_ZA, SOTRING_PRICE_ASC, SOTRING_PRICE_DESC
What is constants? How to get it? Should I install it somehow?

2022-11-19 22:33 UTC, rgirl0801 commented on tests/test_inventory.py
> +from constants import SOTRING_AZ, SOTRING_ZA, SOTRING_PRICE_ASC, SOTRING_PRICE_DESC
No, I think, you should delete them.

2022-11-19 23:25 UTC, akioikeda requested changes
- In my case the test is failing here:
FAILED tests/test_inventory.py::TestCartClass::test_change_add_button_text - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="add-to-cart-sauce-labs-bike-light"]
Please fix
- fix import

2022-11-19 23:39 UTC, rgirl0801 commented on tests/test_inventory.py
> +from constants import SOTRING_AZ, SOTRING_ZA, SOTRING_PRICE_ASC, SOTRING_PRICE_DESC
Done

2022-11-19 23:47 UTC, rgirl0801 commented
> * In my case the test is failing here:
>   FAILED tests/test_inventory.py::TestCartClass::test_change_add_button_text - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="add-to-cart-sauce-labs-bike-light"]
>   Please fix
> * fix import

Sounds weird. 
Because my test failed by reason of:
FAILED tests/test_inventory.py::TestCartClass::test_change_add_button_text - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="user-name"]
However, it works in another case(test_change_bage_when_adding e.g.)

2022-11-20 00:01 UTC, akioikeda commented
> > * In my case the test is failing here:
> >   FAILED tests/test_inventory.py::TestCartClass::test_change_add_button_text - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="add-to-cart-sauce-labs-bike-light"]
> >   Please fix
> > * fix import
> 
> Sounds weird. Because my test failed by reason of: FAILED tests/test_inventory.py::TestCartClass::test_change_add_button_text - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="user-name"] However, it works in another case(test_change_bage_when_adding e.g.)

Could you please run tests again on your system?

2022-11-20 15:38 UTC, closed without merging